I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/fourth_task.rpy", line 144, in script
    jump finish_game
ScriptError: could not find label 'finish_game'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/fourth_task.rpy", line 144, in script
    jump finish_game
  File "C:\renpy\renpy_inst\inner\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\renpy\renpy_inst\inner\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'finish_game'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Пушистые IT 0.0
Wed Dec 14 01:46:19 2022
